import { SelectProps } from "antd";

export const INTRESTS_OPTIONS: SelectProps["options"] = [
  { value: "JDM", label: "JDM" },
  { value: "Muscle Cars", label: "Muscle Cars" },
  { value: "European Sports Cars", label: "European Sports Cars" },
  { value: "Classic Cars", label: "Classic Cars" },
  { value: "Off-Road Vehicles", label: "Off-Road Vehicles" },
  { value: "Supercars", label: "Supercars" },
  { value: "Tuner Cars", label: "Tuner Cars" },
  { value: "Electric Vehicles", label: "Electric Vehicles" },
  { value: "Rally Cars", label: "Rally Cars" },
  { value: "Hot Rods", label: "Hot Rods" },
  { value: "Luxury Cars", label: "Luxury Cars" },
  { value: "Drift Cars", label: "Drift Cars" },
  { value: "Vintage Trucks", label: "Vintage Trucks" },
  { value: "Modified Cars", label: "Modified Cars" },
  { value: "Lowriders", label: "Lowriders" },
  { value: "Cars and Coffee", label: "Cars and Coffee" },
  { value: "Park and Chill", label: "Park and Chill" },
  { value: "Daytime Meet", label: "Daytime Meet" },
  { value: "Nighttime Meet", label: "Nighttime Meet" },
  { value: "Cruise Night", label: "Cruise Night" },
  { value: "Show and Shine", label: "Show and Shine" },
  { value: "Car Show", label: "Car Show" },
  { value: "Cars and Coffees", label: "Cars and Coffees" },
  { value: "Meet and Greet", label: "Meet and Greet" },
  { value: "Pop-Up Meet", label: "Pop-Up Meet" },
];

export const US_STATES_OPTIONS: SelectProps["options"] = [
  { value: "AL", label: "Alabama" },
  { value: "AK", label: "Alaska" },
  { value: "AZ", label: "Arizona" },
  { value: "AR", label: "Arkansas" },
  { value: "CA", label: "California" },
  { value: "CO", label: "Colorado" },
  { value: "CT", label: "Connecticut" },
  { value: "DE", label: "Delaware" },
  { value: "FL", label: "Florida" },
  { value: "GA", label: "Georgia" },
  { value: "HI", label: "Hawaii" },
  { value: "ID", label: "Idaho" },
  { value: "IL", label: "Illinois" },
  { value: "IN", label: "Indiana" },
  { value: "IA", label: "Iowa" },
  { value: "KS", label: "Kansas" },
  { value: "KY", label: "Kentucky" },
  { value: "LA", label: "Louisiana" },
  { value: "ME", label: "Maine" },
  { value: "MD", label: "Maryland" },
  { value: "MA", label: "Massachusetts" },
  { value: "MI", label: "Michigan" },
  { value: "MN", label: "Minnesota" },
  { value: "MS", label: "Mississippi" },
  { value: "MO", label: "Missouri" },
  { value: "MT", label: "Montana" },
  { value: "NE", label: "Nebraska" },
  { value: "NV", label: "Nevada" },
  { value: "NH", label: "New Hampshire" },
  { value: "NJ", label: "New Jersey" },
  { value: "NM", label: "New Mexico" },
  { value: "NY", label: "New York" },
  { value: "NC", label: "North Carolina" },
  { value: "ND", label: "North Dakota" },
  { value: "OH", label: "Ohio" },
  { value: "OK", label: "Oklahoma" },
  { value: "OR", label: "Oregon" },
  { value: "PA", label: "Pennsylvania" },
  { value: "RI", label: "Rhode Island" },
  { value: "SC", label: "South Carolina" },
  { value: "SD", label: "South Dakota" },
  { value: "TN", label: "Tennessee" },
  { value: "TX", label: "Texas" },
  { value: "UT", label: "Utah" },
  { value: "VT", label: "Vermont" },
  { value: "VA", label: "Virginia" },
  { value: "WA", label: "Washington" },
  { value: "WV", label: "West Virginia" },
  { value: "WI", label: "Wisconsin" },
  { value: "WY", label: "Wyoming" },
];
